coursefeedback/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^$', 'feedback.views.home', name='home'),
    url(r'^feedback/', include('feedback.urls', namespace="feedback")),
    url(r'^getmail/', 'feedback.views.getmail', name='getmail'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^instructions/$', 'feedback.views.instruction', name='instruction'),
    url(r'^analytics/(?P<br>[A-Za-z]{2})/$', 'feedback.views.analytics'),
    url(r'^login/$', 'feedback.views.login_user', name='login_user'),
    url(r'^analytics/$', 'feedback.views.depart', name='department'),
    url(r'^logout/$', 'feedback.views.logout_user', name='logout_user'),
    url(r'^credits/$', 'feedback.views.credits', name='credits'),
    )

feedback/urls.py
__author__ = 'HIRENDRA'

from django.conf.urls import patterns, url

from feedback import views

urlpatterns = patterns('',
                       url(r'^(?P<key>\w+)/$',views.index, name='index'),
                       url(r'^getmail/$',views.getmail, name='getmail'),
                       url(r'^(?P<prof_pk>\d+)/(?P<stud_roll>\w+)/(?P<sub_pk>\d+)/(?P<key>\w+)/$',views.polls, name='polls'),
                       url(r'^analyse/$',views.analyse, name='analyse'),
                       url(r'^analyse/(?P<prof_pk>\d+)/$',views.courseanalyse, name='courseanalyse'),

                        )

feedback/models.py
from django.db import models
from datetime import datetime

class Student(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    roll_no = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    branch=models.CharField(max_length=100)
    semester=models.IntegerField(max_length=2)
    student_date=models.DateTimeField(default=datetime.now())
    course_type=models.CharField(max_length=20)
    key = models.CharField(max_length = 25)


    def was_published_recently(self):
        return self.student_date<=datetime.now()
    was_published_recently.admin_order_field = 'student_date'
    #to display an icon other than boolean information
    was_published_recently.boolean = True
    # to display a name to the column
    was_published_recently.short_description = 'Added Recently'

    def __str__(self):
        return self.roll_no

class dept(models.Model):
    dept_code = models.CharField(max_length=2, primary_key=True)
    dept_name = models.CharField(max_length=150) # HOD
    def __str__(self):              # __unicode__ on Python 2
        return self.dept_name

class Subject(models.Model):
    students=models.ManyToManyField(Student)
    subject_code = models.CharField(max_length=20)
    subject_name= models.CharField(max_length=200)
    subject_date = models.DateTimeField(default=datetime.now())


    def was_published_recently(self):
        return self.subject_date<datetime.now()
    was_published_recently.admin_order_field = 'subject_date'
    #to display an icon other than boolean information
    was_published_recently.boolean = True
    # to display a name to the column
    was_published_recently.short_description = 'Added Recently'
    def __str__(self):
        return self.subject_code


class Professor(models.Model):
    prof_name=models.CharField(max_length=100)
    prof_id = models.CharField(max_length=20)
    dept=models.CharField(max_length=4)
    prof_date = models.DateTimeField(default=datetime.now())

    def was_published_recently(self):
        return self.prof_date<=datetime.now()
    was_published_recently.admin_order_field = 'prof_date'
    #to display an icon other than boolean information
    was_published_recently.boolean = True
    # to display a name to the column
    was_published_recently.short_description = 'Added Recently?'

    def __str__(self):
        return self.prof_name

class Course(models.Model):
    subject = models.ForeignKey(Subject)
    professor=models.ForeignKey(Professor)
    prof_date = models.DateTimeField(default=datetime.now())

    def __unicode__(self):
        return u'%s %s' % (self.subject, self.professor)


class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    question_date= models.DateTimeField(default=datetime.now())
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.question_date<=datetime.now()
    was_published_recently.admin_order_field = 'question_date'
    #to display an icon other than boolean information
    was_published_recently.boolean = True
    # to display a name to the column
    was_published_recently.short_description = 'Published Recently?'

class Result(models.Model):
    question = models.ForeignKey(Question)
    course = models.ForeignKey(Course)
    excellent_votes = models.IntegerField(default = 0)
    verygood_votes = models.IntegerField(default = 0)
    good_votes = models.IntegerField(default = 0)
    fair_votes = models.IntegerField(default = 0)
    poor_votes = models.IntegerField(default = 0)
    total_votes = models.IntegerField(default = 0)

    def __unicode__(self):
        return u'%s %s' %(self.course, self.question)

class Done(models.Model):
    course=models.ForeignKey(Course)
    student=models.ForeignKey(Student)
    done=models.IntegerField(max_length=1,default=0)

    def __unicode__(self):
        return u'%s   %s    %s' % (self.student, self.course, self.done)

class Comment(models.Model):
    course= models.ForeignKey(Course)
    comment_1 = models.CharField(max_length=1000, null=True, blank=True)
    comment_2 = models.CharField(max_length=1000, null=True, blank=True)
    comment_3 = models.CharField(max_length=1000, null=True, blank=True)
    comment_4 = models.CharField(max_length=1000, null=True, blank=True)

    def __unicode__(self):
        return u'%s' %(self.course)

feedback/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Student, Subject, Question, Course, Professor, Result, Done,dept,Comment
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import string
import random
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages

def credits(request):
    return render(request,'feedback/credits.html')
def analytics(request,br):
    if not request.user.is_authenticated():
        return render(request,'feedback/denied.html')
    students=Student.objects.filter(branch__startswith=br)
    Total_Done=Done.objects.filter(student=students).count()
    Actual_Done=Done.objects.filter(student=students,done=1).count()
    faculty=Professor.objects.filter(dept__startswith=br).order_by('prof_name')
    course=Course.objects.filter(professor=faculty)
    comments=Comment.objects.filter(course=course)
    question=Question.objects.get(pk=21)
    result=Result.objects.filter(course=course).order_by('course')
    total=Result.objects.filter(course=course,question=question).count()
    result_count=Result.objects.filter(course=course,question=question,total_votes__gt=0).count()
    context={'faculty':faculty,'course':course,'result':result,'question':question,'comments':comments,'result_count':result_count,'total':total,'Total_Done':Total_Done,'Actual_Done':Actual_Done}

    return render(request,'feedback/analytics.html',context)

def depart(request):
    if not request.user.is_authenticated():
        return render(request,'feedback/denied.html')
    department=dept.objects.all()
    subject=Subject.objects.all().count()
    course=Course.objects.all().count()
    COURSE=Course.objects.all()
    done=Done.objects.filter(done=1).count()
    total=Done.objects.all().count()
    question=Question.objects.get(pk=21)
    student=Student.objects.all().count()
    result_count=Result.objects.filter(course=COURSE,question=question,total_votes__gt=0).count()
    return render(request,'feedback/all_department.html',{'dept':department,'subject':subject,'course':course,'done':done,'total':total,'student':student,'result_count':result_count})
def home(request):
    return render(request, 'feedback/getmail.html')

def logout_user(request):
    if request.user.is_authenticated():
        logout(request)
        state="You have been successfully logged out."
        messages.success(request,state)
    else:
        state="Oops ! You are already logged out ! Try logging in again"
        messages.error(request,state)
    return render(request, 'feedback/logged_out.html')

def index(request,key):
    #user = get_object_or_404(User,first_name=key)
    #user=User.objects.get(first_name=key)
    student = Student.objects.get(key = key)
    done_list = student.done_set.all()
    request.session['key']="Hello"
    request.session['fav_color'] = 'blue'
    return render(request, 'feedback/course2.html', {'student': student, 'done_list': done_list, 'key':key})


def polls(request, prof_pk, stud_roll, sub_pk, key):
    #student = get_object_or_404(Student, roll_no=stud_roll)
    #professor = get_object_or_404(Professor,id=prof_pk)
    #subject = get_object_or_404(Subject, id=sub_pk)
    student = Student.objects.get(roll_no = stud_roll)
    professor  = Professor.objects.get(id = prof_pk)
    subject = Subject.objects.get(id = sub_pk)
    #user = get_object_or_404(User, first_name=key)
    #key=user.first_name
    course = Course.objects.filter(subject=subject, professor=professor)
    course = course[0]
    d = student.done_set.all()
    result_list = course.result_set.all()

    for done in d:
        if done.course == course:
            if done.student == student:
                key = done.done
    if not key:
        if request.method == "POST":
            for result in result_list:
                choice = request.POST.get(result.question.question_text)
                if choice == 'excellent':
                    result.excellent_votes += 1
                    result.save()
                elif choice == 'verygood':
                    result.verygood_votes += 1
                    result.save()
                elif choice == 'good':
                    result.good_votes += 1
                    result.save()
                elif choice == 'fair':
                    result.fair_votes += 1
                    result.save()
                elif choice == 'poor':
                    result.poor_votes += 1
                    result.save()

                result.total_votes = (
                        result.excellent_votes + result.verygood_votes + result.good_votes + result.fair_votes + result.poor_votes)
                result.save()

            comment_text1 = request.POST.get("comment_1")
            comment_text2 = request.POST.get("comment_2")
            comment_text3 = request.POST.get("comment_3")
            comment_text4 = request.POST.get("comment_4")
            course.comment_set.create(comment_1=comment_text1,
                                      comment_2=comment_text2,
                                      comment_3=comment_text3,
                                      comment_4=comment_text4, )

            for done in d:
                if done.course == course:
                    if done.student == student:
                        done.done = 1
                        done.save()
            #return HttpResponseRedirect(reverse("/feedback/"+str(user.first_name)+"/"))
            #return HttpResponseRedirect(reverse("{% url 'feedback:index' user.first_name %}"))
            messages.success(request,"Feedback Submission Successful")
            url='/feedback/'+student.key+'/'
            return HttpResponseRedirect(url)

        else:
            return render(request, 'feedback/questions2.html', {'result_list1': result_list[:5],
                                                                    'result_list2': result_list[5:10],
                                                                    'result_list3': result_list[10:14],
                                                                    'result_list4': result_list[14:19],
                                                                    'result_list5': result_list[19:21],
                                                                    'course': course,
                                                                    'professor': professor,
                                                                    'subject': subject,
                                                                    'key':student.key,})
    else:
        messages.error(request,"Oops! You have already submitted this feedback")
        url='/feedback/'+student.key+'/'
        return HttpResponseRedirect(url)




@login_required(login_url='/login/')
def analyse(request):
    if request.user.is_authenticated():
        if request.user.is_staff:
            professor_list = Professor.objects.all()
            return render(request, 'feedback/analyse.html', {'professor_list': professor_list})
        else:
            return HttpResponse("Not a valid memeber")
    else:
        return HttpResponse("Please Login First")


@login_required(login_url='/login/')
def courseanalyse(request, prof_pk):
    if request.user.is_authenticated():
        if request.user.is_staff:
            professor = Professor.objects.get(pk=prof_pk)
            course_list = professor.course_set.all()

            return render(request, 'feedback/courseanalyse.html', {'course_list': course_list, 'professor': professor})
        else:
            return HttpResponse("Not a valid memeber")
    else:
        return HttpResponse("Please Login First")


def getmail(request):
    email = request.POST.get('email')
    if not email in [user.username for user in User.objects.all()]:
        return render(request, 'feedback/invalid.html')
    else:
        s = Student.objects.filter(email = email)
        key = s[0].key
        text = "Submit the coursefeedback form by clicking this link: http://10.1.1.239/feedback/"+key+"/ or http://14.139.41.172/feedback/"+key+"/"
        send_mail('Course Feedback Portal', text, settings.EMAIL_HOST_USER, [email], fail_silently=False)
        messages.success(request,'An email has been sent to your email address.Please Follow the link in the email')
        #return HttpResponse("<b>An email has been sent to your email address.Please Follow the link in the email</b>")
        return HttpResponseRedirect('/')
def instruction(request):
    return render(request, 'feedback/instructions.html')

def login_user(request):

    username = password = ''
    if request.user.is_authenticated():
        #state="Already logged in, "+request.user.username
        return HttpResponseRedirect('/analytics')
    if request.POST:
        username = request.POST['username']
        password = request.POST['pass']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect('/analytics')
            else:
                state = "Your account is not active, please contact the site admin."
        else:
            state = "Your username and/or password were incorrect."
            messages.error(request,state)

    return render(request, 'feedback/login.html')

feedback/templates/feedback/all_department.html
{% extends "feedback/index.html" %}
  {% block body  %}
<div class="row">
    <p> Click on any department to view feedback of faculty of that department.</p>
    <table class="table table-bordered"><tbody><tr><th colspan="2" style="text-align:center;"><h4>Summary of Feedback Response</h4></th></tr>

 <tr><th><b>Total number of Course-Faculty pairs populated </b></th><th>{{course}}</th></tr>

    <tr><th><b>Course-Faculty pair for which atleast one feedback is received </b></th><th>{{result_count}}</th></tr>
    <tr><th><b>Total number of Students: </b></th><th>{{student}}</th></tr>
    <tr><th><b>Total number of feedback for submission: </b></th><th>{{total}}</th></tr>
     <tr><th><b>Actual number of feedback received: </b></th><th>{{done}}</th></tr>


    </tbody></table>
    {% for department in dept %}
   <p class="msg"><b> <span class="firstcharacter"> {{ forloop.counter }}.</span>  {{department}} </b>
       <a class="btn btn-info ripple-effect pull-right" href="{{department.dept_code}}">Click Here</a> </p>
    {% endfor %}
</div>
{% endblock %}

feedback/templates/feedback/analyse.html
<!DOCTYPE html>
{% extends "feedback/layout.html" %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
{% block body %}
<body>

<div class="wrapper col4">
    <div id="container">
        <h5><b>List of Courses and Instructors</b></h5>
    {% for professor in professor_list %}
        <a href = "{% url 'feedback:courseanalyse' professor.id %}">{{professor.prof_name}}</a><br>
    {% endfor %}
    </div>
    </div>
</body>
{% endblock %}
</html>

feedback/templates/feedback/analytics.html
{% extends "feedback/index.html" %}
  {% block body  %}
<h3 style="padding:10px;font-size:25px; border: none;" class="btn-magick"><span class="glyphicon glyphicon-list-alt"></span> Department Wise Analytics:</h3>
<p>Page may take some time to load completely.</p>
<table class="table table-bordered"><tbody><tr><th colspan="2" style="text-align:center;"><h4>Overview</h4></th></tr>

    <tr><th><b>Total number of Course-Faculty pairs populated </b></th><th>{{total}}</th></tr>

    <tr><th><b>Course-Faculty pair for which atleast one feedback is received </b></th><th>{{result_count}}</th></tr>
<tr><th><b>Total number of feedback expected for course-faculty pair </b></th><th>{{Total_Done}}</th></tr>
<tr><th><b>Actual number of feedback received for course-faculty pair </b></th><th>{{Actual_Done}}</th></tr>

</tbody>
    </table>
{% for f in faculty %}
<div class="panel panel-success">
                <div class="panel-heading ripple-effect">
                    <h3 class="panel-title"><h4><b> {{forloop.counter}}.</b> {{ f.prof_name }}</h4></h3>
                    <span class="pull-right "><i class="glyphicon glyphicon-minus"></i></span>
                </div>
                <div class="panel-body">

<p>In this section, you will see the feedback response of all courses taught by <b>{{ f.prof_name }}</b>.</p>

        {% for Course in course %}
                    {% if f == Course.professor  %}
                   <h4 class="btn-magick btn-lg">  <b><span class="glyphicon glyphicon-circle-arrow-right"></span> {{Course.subject}} {{Course.subject.subject_name}}</b> </h4>
                       {% for result in result %}
                        {% if Course == result.course and f == result.course.professor and result.question == question %}
 <p id="msg{{result.pk}}"> Sorry no votes has been recieved for this course-faculty pair.  </p>
                   <div class="progress" style="height:22px;display:none;" id="progress{{result.pk}}">

  <div class="progress-bar progress-bar-success " role="progressbar" id="progressBar1{{result.pk}}" style="width:20%;">
    20% Excellent Votes
  </div>
  <div class="progress-bar progress-bar-info" role="progressbar"  id="progressBar2{{result.pk}}" style="width:20%;">
    20% Very Good Votes
  </div>
  <div class="progress-bar progress-bar-default" role="progressbar" id="progressBar3{{result.pk}}"  style="width:20%;">
    20% Good Votes
  </div>
                       <div class="progress-bar progress-bar-warning" role="progressbar" id="progressBar4{{result.pk}}"  style="width:20%;">
    20% Fair Votes
  </div>
                        <div class="progress-bar progress-bar-danger" role="progressbar" id="progressBar5{{result.pk}}"  style="width:20%;">
20% Poor Votes
  </div>
</div>
                    {% if result.total_votes > 0 %}

    <script type="text/javascript">

        var a= {{result.excellent_votes}};
        a = parseInt(a,10);

        var b={{result.verygood_votes}};
        b = parseInt(b,10);
        var c={{result.good_votes}};
        c = parseInt(c,10);
        var d= {{result.fair_votes}}
        d = parseInt(d,10);
        var e={{result.poor_votes}};
        e = parseInt(e,10);
        var f={{result.total_votes}}
        f = parseInt(f,10);
        f=a+b+c+d+e;
        if(f >0) {
        a=a/f*100;
        b=b/f*100;
        c=c/f*100;
        d=d/f*100;


        a=Math.round(a*100)/100;
        b=Math.round(b*100)/100;
        c=Math.round(c*100)/100;
        d=Math.round(d*100)/100;

        e=100-(a+b+c+d);
        e=Math.floor(e*100)/100;
        a = a.toString()+'%';
        b = b.toString()+'%';
        c = c.toString()+'%';
        d = d.toString()+'%';
        e = e.toString()+'%';
        document.getElementById('progress{{result.pk}}').style.display='block';

        document.getElementById('progressBar1{{result.pk}}').style.width=a;
        document.getElementById('progressBar1{{result.pk}}').innerHTML = a+" Excellent Votes";
        document.getElementById('progressBar2{{result.pk}}').style.width=b;
        document.getElementById('progressBar3{{result.pk}}').style.width=c;
        document.getElementById('progressBar4{{result.pk}}').style.width=d;
        document.getElementById('progressBar5{{result.pk}}').style.width=e;
        document.getElementById('progressBar2{{result.pk}}').innerHTML = b+" Very Good Votes";
        document.getElementById('msg{{result.pk}}').innerHTML = "Here's the graphical view for response of  <i>Overall Rating of the teacher</i>, as recorded by portal:";
        document.getElementById('progressBar3{{result.pk}}').innerHTML = c+ " Good Votes";
        document.getElementById('progressBar4{{result.pk}}').innerHTML = d+" Fair Votes";
        document.getElementById('progressBar5{{result.pk}}').innerHTML = e+" Poor Votes";
}
{% endif %}
    </script>
                        {% endif %}
                        {% endfor %}
                    <div class="row" id="show{{Course.pk}}">
                    <div class="col-sm-3">
                  <a href="javascript:void(0)" onclick="show('{{Course.pk}}')"><span class="glyphicon glyphicon-cloud-download"></span> Show/Hide Question Responses</a></div>
                     <div class="col-sm-3">
                    <a href="javascript:void(0)" onclick="show('{{Course.pk}}comment_1')"><span class="glyphicon glyphicon-cloud-download"></span> Show/Hide Comments On Course Organisation</a> </div>
                   <div class="col-sm-3">
                    <a href="javascript:void(0)" onclick="show('{{Course.pk}}comment_2')"><span class="glyphicon glyphicon-cloud-download"></span> Show/Hide Comment On Presentation</a></div>
                    <div class="col-sm-3">

                    <a href="javascript:void(0)" onclick="show('{{Course.pk}}comment_3')"><span class="glyphicon glyphicon-cloud-download"></span> Show/Hide Comment On Interaction and Rapport</p></a></div>
 <div class="col-sm-3">
                    <a href="javascript:void(0)" onclick="show('{{Course.pk}}comment_4')"><span class="glyphicon glyphicon-cloud-download"></span>Show/Hide Comment On Examinations and Grading</p></a></div>

</div>

                    <div class="row" id="{{Course.pk}}comment_1" style="display:none;">
                        <h4>&nbsp;&nbsp;<span class="glyphicon glyphicon-tasks"></span> Comments On Course Organisation</h4>
                        <div class="msg msg-success">
                        {% for comment in comments %}

                        {% if comment.course == Course %}
                            {% if comment.comment_1 %}
                        <p><span class="glyphicon glyphicon-comment"></span> {{comment.comment_1}}</p>
{% endif %}
                        {% endif %}

                        {% endfor %} </div>

                    </div>

                    <div class="row" id="{{Course.pk}}comment_2" style="display:none;">
                        <h4>&nbsp;&nbsp;<span class="glyphicon glyphicon-tasks"></span> Comment On Presentation </h4>
                        <div class="msg msg-success">
                        {% for comment in comments %}

                        {% if comment.course == Course %}
                            {% if comment.comment_2 %}
                        <p><span class="glyphicon glyphicon-comment"></span> {{comment.comment_2}}</p>
{% endif %}
                        {% endif %}

                        {% endfor %} </div>

                    </div>




                    <div class="row" id="{{Course.pk}}comment_3" style="display:none;">
                        <h4>&nbsp;&nbsp;<span class="glyphicon glyphicon-tasks"></span> Comment On Interaction and Rapport </h4>
                        <div class="msg msg-success">
                        {% for comment in comments %}

                        {% if comment.course == Course %}
                            {% if comment.comment_3 %}
                        <p><span class="glyphicon glyphicon-comment"></span> {{comment.comment_3}}</p>
{% endif %}
                        {% endif %}

                        {% endfor %} </div>

                    </div>





                    <div class="row" id="{{Course.pk}}comment_4" style="display:none;">
                        <h4>&nbsp;&nbsp;<span class="glyphicon glyphicon-tasks"></span>
 Comment On Examinations and Grading </h4>
                        <div class="msg msg-success">
                        {% for comment in comments %}

                        {% if comment.course == Course %}
                            {% if comment.comment_4 %}
                        <p><span class="glyphicon glyphicon-comment"></span> {{comment.comment_4}}</p>
{% endif %}
                        {% endif %}

                        {% endfor %} </div>

                    </div>


<div id="{{Course.pk}}" class="row" style="display:none;">
    <br>

{% for result in result %}
                    {% if Course == result.course and f == result.course.professor %}
   <div class="msg msg-magick"><p><span class="glyphicon glyphicon-chevron-right"></span> <b>{{result.question}}</b>
      <span style="color:green;"><br>Vote Results</span>  <b>Total Votes:</b> {{result.total_votes}} <span class="pull-right"><b>Excellent: </b> {{result.excellent_votes}}
        <b>Very Good :</b> {{result.verygood_votes}}
        <b>Good : </b> {{result.good_votes}}
        <b>Fair : </b> {{result.fair_votes}}
       <b>Poor : </b> {{result.poor_votes}}</span>
                   </p> </div>


                    {% endif %}
                    {% endfor %}
    </div>




{% endif %}

{% endfor %}


	</div>



             </div>
{% endfor %}

                      <script>

    function show(one) {
   if( document.getElementById(one).style.display === 'block')
   {
   document.getElementById(one).style.display = 'none';
   }

   else
   {
   document.getElementById(one).style.display = 'block';
   }



}
</script>
{% endblock %}

feedback/templates/feedback/course2.html
<!DOCTYPE html>

{% extends "feedback/layout.html" %}
<html>
<head lang="en">
    <meta charset="UTF-8">
   {% block title %} <title> STUDENTS'S FEEDBACK ON COURSES EVEN SEMESTER 2014-15</title> {% endblock %}
</head>
{% block nav %}
<div class="wrapper col2">
  <div id="topnav">
   <ul><li><a href="/">Home</a></li><li> &#9658;</li><li><a href="#"></a> Course Dashboard </li><li> &#9658;</li>

       </ul>
      </div>
    </div>
{% endblock %}
<body>
{% block body %}
<div class="row" >
    <div class="timeline" style="margin-left:30px;">
	<div class="row"  >
		<div class="col-md-4 bg_blur " style="background-image: url('/static/images/bg.jpg')">
    	   <!--  <a href="#" class="follow_btn hidden-xs">VISIT</a> -->
		</div>
        <div class="col-md-8  col-xs-12" >
           <img src="/static/feedback/images/profile.png" class="img-thumbnail picture hidden-xs" />
           <img src="/static/feedback/images/profile.png" class="img-thumbnail visible-xs picture_mob" />
           <div class="header">
                <h1>Hello, {{student.name}}</h1>

                
                <span>Even though you have logged into the system using your login credentials,
your identity for feedback is kept anonymous.
</span>
           </div>
        </div>
    </div>
</div>
<!-- <div class="row msg msg-danger">
   <p>

<b><span style="color:green">Hello, {{student.name}} </span>,<br>
    Even though you have logged into the system using your login credentials,
your identity for feedback is kept anonymous.</b></div> -->
<div class="row msg msg-magick">
<p>
Following are the courses you have undergone during the recently concluded semester. Please give your feedback for all the courses. 
If the course is taught by more than one faculty member, the course will appear multiple times, together with the name of
each of the faculty members. The feedback needs to be given teacher-wise.</p> </div>
<div class="row">

<div class="table-responsive-vertical shadow-z-1 table-bordered " style="-webkit-box-shadow: 0 1px 3px 0 rgba(0,0,0,.12),
                      0 1px 2px 0 rgba(0,0,0,.24);
  -moz-box-shadow:    0 1px 3px 0 rgba(0,0,0,.12),
                      0 1px 2px 0 rgba(0,0,0,.24);
  box-shadow:         0 1px 3px 0 rgba(0,0,0,.12),
                      0 1px 2px 0 rgba(0,0,0,.24">
  <!-- Table starts here -->
  <table id="table" class="table">
    <thead style="background:#8B497E; color:#e6e6fa;"><th>Course Code</th>
    <th>Course Name</th>
    <th> Faculty</th>
    <th> Status</th>
    <th>Action</th>
    </thead>
{% for done in done_list %}


                <tr>
                    <td> <b>{{done.course.subject.subject_code}} </b></td>
              <td> <b>{{done.course.subject.subject_name}}</b> </td>
               <td> <b> {{done.course.professor.prof_name}} </b></td>
                     {% if done.done %} <td>Done <span style="color:green;" class="glyphicon glyphicon-ok-sign"></span></td>
                    <td>None</td>
                        {% else %}<td> Pending <span style="color:red;" class="glyphicon glyphicon-remove-circle"></span></td>
                    <td><a href = "{% url 'feedback:polls' done.course.professor.id student.roll_no done.course.subject.id key %}">Fill Feedback</a></td>
                {% endif %} </tr>






{% endfor %}
</table>
    </div></div></div>
<!--
<h5 class="msg msg-success"><b>Comp leted Feedback Courses</b></h5>
<p> In this </p>
{% for done in done_list %}
    {% if done.done %}
        <li style="font-size:18px;">
                <b>{{done.course.subject.subject_code}} </b><br>
                {{done.course.subject.subject_name}}<br>
                {{done.course.professor.prof_name}}- Done
                <br>
        </li>
    {% endif %}
{% endfor %}
<h5><b> Pending List of Courses For Feedback</b></h5>
{% for done in done_list %}
        {% if not done.done %}

        <li style="font-size:18px;">
           <b> {{done.course.subject.subject_code}} </b> <br>
            {{done.course.subject.subject_name}}<br>
            <ol><a href = "{% url 'feedback:polls' done.course.professor.id student.roll_no done.course.subject.id key %}">
                {{done.course.professor.prof_name}}</a></ol>
            <br>
        </li>
    {% endif %}
{% endfor %}


</div>-->
   
{% endblock %} 
</body>

</html>